services:
  # Design System
  - type: web
    name: Design System
    env: static
    branch: master
    repo: git@github.com:heather-turano-coaching/heather-turano-coaching.git
    buildCommand: npm run build:components:storybook
    staticPublishPath: ./packages/components/storybook-static
    domains:
      - design.livelifemindful.com
    envVars:
      - fromGroup: npm

  # Websites
  - type: web
    name: Live Life Mindful
    env: static
    branch: master
    repo: git@github.com:heather-turano-coaching/heather-turano-coaching.git
    buildCommand: npm run build:live-life-mindful
    staticPublishPath: ./packages/websites/live-life-mindful/public
    domains:
      - livelifemindful.com
    envVars:
      - fromGroup: npm
      - fromGroup: htc-ghost
      - fromGroup: htc-contentful
      - key: COMMENTO_ORIGIN
        sync: false

  - type: web
    name: 100 Days of Mindful Movement
    env: static
    branch: master
    repo: git@github.com:heather-turano-coaching/heather-turano-coaching.git
    buildCommand: npm run build:mindful-movement
    staticPublishPath: ./packages/websites/mindful-movement/public
    domains:
      - mindfulmovement100.com
    envVars:
      - fromGroup: npm
      - fromGroup: htc-contentful
      - key: HTC_MINDFUL_MOVEMENT_CONTENTFUL_SPACE_ID
        sync: false
      - key: HTC_MINDFUL_MOVEMENT_CONTENTFUL_ACCESS_TOKEN
        sync: false
      - key: GATSBY_HTC_API
        sync: https://api.heatherturanocoaching.com

  # API
  - type: web
    name: Api
    env: node
    branch: master
    repo: git@github.com:heather-turano-coaching/heather-turano-coaching.git
    buildCommand: npm run build:platform
    startCommand: npm run serve:platform
    domains:
      - api.heatherturanocoaching.com
    envVars:
      - key: HTC_DB_CONNECTION_STRING
        fromDatabase:
          name: htc-db
          property: connectionString
      - key: HTC_MINDFUL_MOVEMENT_REDIRECT_ROOT_URL
        value: https://mindfulmovement100.com

  - type: web
    name: Ghost
    env: docker
    dockerfilePath: ./ghost/Dockerfile
    dockerContext: ./ghost
    branch: master
    repo: git@github.com:heather-turano-coaching/heather-turano-coaching.git
    domains:
      - admin.blog.livelifemindful.com
    disk:
      name: ghost
      mountPath: /var/lib/ghost/content
      sizeGB: 10
    envVars:
      - key: url
        value: https://admin.blog.livelifemindful.com
      - key: mail__transport
        value: SMTP
      - key: mail__from
        value: "'Heather Turano' <heather@livelifemindful.com>"
      - key: mail__options__service
        value: Mailgun
      - key: mail__options__host
        value: smtp.mailgun.org
      - key: mail__options__port
        value: 465
      - key: mail__options__secureConnection
        value: true
      - key: mail__options__auth__user
        value: postmaster@mail.livelifemindful.com
      - key: mail__options__auth__pass
        sync: false

  - type: web
    name: Commento
    env: docker
    dockerfilePath: ./commento/Dockerfile
    dockerContext: ./commento
    branch: master
    repo: git@github.com:heather-turano-coaching/heather-turano-coaching.git
    domains:
      - community.blog.livelifemindful.com
    envVars:
      - key: COMMENTO_ORIGIN
        value: https://community.blog.livelifemindful.com
      - key: COMMENTO_SMTP_HOST
        value: smtp.mailgun.org
      - key: COMMENTO_SMTP_PORT
        value: 587
      - key: COMMENTO_SMTP_USERNAME
        value: comments@mail.livelifemindful.com
      - key: COMMENTO_SMTP_FROM_ADDRESS
        value: no-reply@livelifemindful.com
      - key: COMMENTO_SMTP_PASSWORD
        sync: false
      - key: COMMENTO_POSTGRES
        fromDatabase:
          name: htc-commento-db-prod
          property: connectionString

databases:
  - name: htc-commento-db-prod
    databaseName: htc_commento_db_prod
    user: admin_prod
  - name: htc-db
    databaseName: htc_db
    user: admin

envVarGroups:
  - name: htc-ghost
    envVars:
      - key: GHOST_API_URL
        value: https://admin.blog.livelifemindful.com
      - key: GHOST_CONTENT_API_KEY
        sync: false
  - name: htc-contentful
    envVars:
      - key: CONTENTFUL_SPACE_ID
        sync: false
      - key: CONTENTFUL_ACCESS_TOKEN
        sync: false
  - name: htc-npm
    envVars:
      - key: FONTAWESOME_NPM_AUTH_TOKEN
        sync: false
