services:
  # Design System
  - type: web
    name: Design System
    env: static
    branch: master
    repo: git@github.com:heather-turano-coaching/heather-turano-coaching.git
    buildCommand: npm run build:components:storybook
    staticPublishPath: ./packages/components/storybook-static
    domains:
      - design.livelifemindful.com
    envVars:
      - fromGroup: npm
envVarGroups:
  - name: htc-ghost
  - envVars:
      - key: GHOST_API_URL
        value: https://admin.blog.livelifemindful.com
      - key: GHOST_CONTENT_API_KEY
        sync: false
  - name: htc-contentful
  - envVars:
      - key: CONTENTFUL_SPACE_ID
        sync: false
      - key: CONTENTFUL_ACCESS_TOKEN
        sync: false
  - name: htc-npm
  - envVars:
      - key: FONTAWESOME_NPM_AUTH_TOKEN
        sync: false
