export { default as Caption } from "./Caption";
export { default as Heading } from "./Heading";
export { default as Paragraph } from "./Paragraph";
export { default as Title } from "./Title";
export { default as Icon } from "./Icon";
export { default as Label } from "./Label";
export { default as Text } from "./Text";
export { default as Markdown } from "./Markdown";
export { default as Color } from "./Color";
