export type Size = "xxs" | "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
export type Position = "left" | "right" | "center";
export type Layout = "inline" | "stacked" | "standalone";
export type Color =
  | "transparent"
  | "lightscale"
  | "lightscale-0"
  | "lightscale-1"
  | "lightscale-2"
  | "lightscale-3"
  | "grayscale"
  | "grayscale-0"
  | "grayscale-1"
  | "grayscale-2"
  | "grayscale-3"
  | "secondary"
  | "secondary-0"
  | "secondary-1"
  | "secondary-2"
  | "secondary-3"
  | "primary"
  | "primary-0"
  | "primary-1"
  | "primary-2"
  | "primary-3"
  | "accent"
  | "accent-0"
  | "accent-1"
  | "accent-2"
  | "accent-3"
  | "success"
  | "success-0"
  | "success-1"
  | "success-2"
  | "success-3"
  | "invalid"
  | "invalid-0"
  | "invalid-1"
  | "invalid-2"
  | "invalid-3";

export type InputStyleType = "primary" | "secondary";
